tree = {
    "root": {
        "Arts and Entertainment" : {
            "Actor Appreciation" : {
                "Contacting Celebrities" : [],
            },
            "Amusement and Theme Parks" : {
                "Carnivals" : [],
                "Disneyland and Disney World" : [],
                "Roller Coasters" : [],
                "Water Parks" : [],
            },
            "Artwork" : {
                "Art Appreciation" : [],
                "Art Collection" : [],
                "Art Equipment" : [],
                "Art Media" : [],
                "Art Studies" : [],
                "Artwork Care and Maintenance" : [],
                "Calligraphy" : [],
                "Careers in Art" : [],
                "Decorating with Prints and Pictures" : [],
                "Exhibited Arts" : [],
                "Framing" : [],
                "Painting" : [],
                "Selling Arts and Crafts" : [],
                "Wall Art" : [],
                "Sculpting" : [],
                "Studios" : [],
            },
            "Books" : {
                "Book Clubs and Book Groups" : [],
                "Borrowing and Sharing Books" : [],
                "Purchasing Books" : [],
                "Specific Book Series" : [],
                "Libraries" : [],
                "EBook Readers" : [],
                "Organizing and Caring for Books" : [],
                "Collecting Books" : [],
                "Selling Books" : [],
            },
            "Concerts" : {
                "Backstage Concerts" : [],
                "Concert Preparation" : [],
                "Concert Safety" : [],
                "Concert Tickets" : [],
                "Dressing for Concerts" : [],
                "Moshing" : [],
                "Music Festivals" : [],
            },
            "Cosplay and Role Playing" : {
                "Cosplay" : [],
                "Role Playing" : [],
                "Furry Fandom" : [],
            },
            "Costumes" : {
                "Animal Costumes" : [],
                "Book and Movie Character Costumes" : [],
                "Cartoon and Comic Character Costumes" : [],
                "Fairy Princess and Doll Costumes" : [],
                "Famous People Costumes" : [],
                "Historical Costumes" : [],
                "Wrestling Costumes" : [],
                "Video Game Character Costumes" : [],
                "Santa Claus Costumes" : [],
                "Star Wars Costumes" : [],
            },
            "Event Tickets" : {
                "Concert Tickets" : [],
            },
            "Fairs and Fetes" : {
                "Carnivals" : [],
                "Science Fair" : [],
            },
            "Festivals" : {
                "Music Festivals" : [],
            },
            "Movies" : {
                "Movie Appreciation" : [],
                "Making Movies" : [],
                "Cinemas" : [],
                "Movie Nights" : [],
                "Movie Collections" : [],
            },
            "Music" : {
                "Musical Instruments" : [],
                "Music Techniques" : [],
                "Orchestra" : [],
                "Singing" : [],
                "Songs and Song Writing" : [],
                "Music Listening and Appreciation" : [],
                "Disc Jockeys" : [],
                "Bands" : [],
                "Music Collectibles" : [],
            },
            "Nightclubs" : {
                "Club Dance" : [],
                "Disco" : [],
            },
            "Parades" : {
            },
            "Parks" : {
                "Botanical Gardens" : [],
                "Dog Parks" : [],
                "National Parks" : [],
                "Zoos" : [],
            },
            "Performing Arts" : {
                "Acting" : [],
                "Theater" : [],
                "Dancing" : [],
                "Talent Shows" : [],
                "Performing Comedy" : [],
                "Circuses" : [],
                "Street Performance" : [],
            },
            "TV Viewing and Shows" : {
                "Doctor Who" : [],
                "My Little Pony: Friendship is Magic" : [],
                "Television Commercials" : [],
            },
        },
        "Cars and Other Vehicles" : {
            "Automotive and Transportation Businesses" : {
            },
            "Automotive Tools" : {
            },
            "Aviation" : {
                "Flight Training" : [],
                "Flight Phases" : [],
                "Cessna Aircraft" : [],
                "Rotorcraft" : [],
                "Unmanned Aerial Vehicles" : [],
                "Air Shows" : [],
                "Air Travel" : [],
                "Aircraft Spotting" : [],
                "Aviation Careers" : [],
            },
            "Bicycles" : {
                "Bicycle Tire Maintenance" : [],
                "Bicycle Brake and Chain Maintenance" : [],
                "Bicycle Theft" : [],
            },
            "Boats" : {
                "Boat Motors and Marine Engines" : [],
                "Transporting and Storing Boats" : [],
                "Purchasing Boats" : [],
                "Boat Building" : [],
                "Boat Service and Repair" : [],
                "Boating Safety" : [],
            },
            "Cars" : {
                "Car Maintenance and Repair" : [],
                "Auto Exterior and Interior Accessories" : [],
                "Renting Cars" : [],
                "Car Makes" : [],
                "Transporting and Storing Cars" : [],
                "Customizing and Modifying Cars" : [],
                "Car Safety and Security" : [],
                "Buying a Car" : [],
                "Car Sales" : [],
                "Car Donations" : [],
                "Car Identification and Registration" : [],
            },
            "Driving Techniques" : {
                "Defensive Driving Skills & Safety" : [],
                "Efficient Driving" : [],
                "Driving Basics" : [],
                "Country Specific Driving Skills" : [],
            },
            "Farm Vehicles" : {
            },
            "Motor Vehicle Accidents" : {
                "First Aid for Traffic Accident Injuries" : [],
                "Motor Vehicle Accidents and Law" : [],
            },
            "Motorcycles" : {
                "Motorcycle Safety" : [],
                "Motorcycle Stunt Riding" : [],
                "Motorcycle Sales" : [],
                "Motorcycle Accessories" : [],
                "Motorcycle Gear" : [],
                "Motorcycle Servicing and Repairs" : [],
                "Transporting and Storing Motorcycles" : [],
                "Modifying Motorcycles" : [],
            },
            "Off Road Vehicles" : {
                "Dirt Bikes" : [],
                "All Terrain Vehicles and Quads" : [],
            },
            "Public Transport" : {
                "Train Travel" : [],
                "Bus Travel" : [],
                "Taxi Cab Travel" : [],
                "Ridesharing" : [],
                "Rapid Transit" : [],
            },


            "Recreational Vehicles" : {
                "Recreational Vehicle Sales and Rental" : [],
                "Mobile Homes" : [],
            },
            "Scooters" : {
                "Kick Scooters" : [],
                "Motorized Scooters" : [],
            },
            "Security and Military Vehicles" : {
            },
            "Trailers" : {
            },
            "Trucks" : {
                "Forklifts" : [],
                "Truck Maintenance" : [],
                "Truck Accessories" : [],
            },
            "Vehicle Loans" : {
                "Car Loans" : [],
            },
            "Vehicle Sports" : {
                "Kart Racing" : [],
                "Vehicle Clubs and Shows" : [],
            },
            "Vehicles and the Law" : {
                "Legal Documents for Driving" : [],
                "Fines and Road Offenses" : [],
                "Driving Under the Influence" : [],
                "Car Identification and Registration" : [],
                "Motor Vehicle Accidents and Law" : [],
                "Vehicle Theft" : [],
            },


        },
        "Computers and Electronics" : {
            "Basic Computer Skills" : {
                "Computer Alarms" : [],
            },
            "Buying Consumer Electronics" : {
                "Selecting and Buying a Computer" : [],
                "Buying Fridges and Freezers" : [],
            },
            "Computer Theft" : {
            },
            "Hacks" : {
            },
            "Hardware" : {
                "External Components" : [],
                "Internal Components" : [],
                "Cabling and Wiring Connection" : [],
            },
            "Internet" : {
                "Downloading" : [],
                "AOL Internet Provider" : [],
                "Wikis" : [],
                "Internet Forums and Message Boards" : [],
                "Internet Security" : [],
                "Internet Browsers" : [],
                "Email and Instant Messaging" : [],
                "Website Application Instructions" : [],
                "Website and Blog Creation" : [],
                "Internet Memes" : [],
                "Internet Streaming Services" : [],
            },
            "Laptops" : {
                "Laptop Batteries" : [],
                "Laptop Maintenance and Repair" : [],
                "MacBook" : [],
                "Chromebook" : [],
            },
            "Maintenance and Repair" : {
                "System Maintenance and Repair" : [],
                "Hardware Maintenance and Repair" : [],
            },
            "Networking" : {
                "Wireless Networking" : [],
            },
            "Operating Systems" : {
                "Linux" : [],
                "Windows" : [],
                "Mac" : [],
            },
            "Phones and Gadgets" : {
                "Bluetooth" : [],
                "Mobile Operating Systems" : [],
                "Robots" : [],
                "Telephone Providers" : [],
                "Calculators" : [],
                "Smartphones" : [],
                "GPS" : [],
                "Portable Media Players" : [],
                "Cell Phones" : [],
                "Communications Monitoring" : [],
                "Mobile Features" : [],
                "Phone Theft" : [],
            },
            "Software" : {
                "Media" : [],
                "Graphics" : [],
                "Install & Uninstall Software" : [],
                "Software Testing" : [],
                "Web Programming" : [],
                "Media Software" : [],
                "MySQL" : [],
                "Adobe Software" : [],
                "CAD Software" : [],
                "Accounting Software" : [],
                "Office" : [],
                "Virtual Machines" : [],
                "File Manipulation" : [],
                "Programming" : [],
                "Migration Software" : [],
            },
            "Tablet Computers" : {
                "Ipad" : [],
                "Microsoft Surface" : [],
            },
            "TV and Home Audio" : {
                "Home Theater" : [],
                "Television" : [],
                "Home Audio" : [],
            },
            "Video Games" : {
                "PC Games" : [],
                "Electronic Game Strategies" : [],
                "Arcade Games" : [],
                "PlayStation Video Game Consoles" : [],
                "Multi Platform Games" : [],
                "Emulators and Roms" : [],
                "Video Game Creation" : [],
                "Nintendo Video Game Consoles" : [],
                "Xbox" : [],
                "Video Game Console Maintenance and Repair" : [],
                "Buying and Selling Video Games" : [],
                "Steam Games" : [],
            },
        },
        "Education and Communications" : {
            "College University and Postgraduate" : {
                "Campus Life" : [],
                "College and University Study Techniques" : [],
                "Budgeting and Financial Aid for College" : [],
                "Applying for Tertiary Education" : [],
                "Studying Overseas" : [],
            },
            "Distance Learning" : {
            },
            "Homeschooling" : {
            },
            "Interview Skills" : {
            },
            "Language Games" : {
                "Codes and Hidden Messaging" : [],
                "Fictional Languages" : [],
            },
            "Learning Techniques and Student Skills" : {
                "Homework Skills" : [],
                "Tests and Exams" : [],
                "Improving And Maintaining Grades" : [],
                "Memorization Skills" : [],
                "Advanced Placement Courses and Exams" : [],
            },
            "Parent Educational Resources" : {
                "Teaching Children Reading and Writing" : [],
                "Helping Children with Homework" : [],
            },
            "Postal System" : {
                "Business Shipping and Delivery" : [],
                "Changing Address" : [],
                "Packing Fragile Items for Shipping" : [],
            },
            "Posters and Signs" : {
            },
            "Preschool and Kindergarten" : {
            },
            "Presentations" : {
                "PowerPoint Presentations" : [],
            },
            "Research and Review" : {
                "Essays" : [],
                "Academic Surveys" : [],
            },
            "Social Activism" : {
                "Environmental Awareness" : [],
                "Volunteer and Community Service" : [],
                "Human Rights" : [],
                "Political Campaigning and Participation" : [],
                "Health Activism" : [],
                "Feminism and Sexism" : [],
                "Racism" : [],
                "Disability Activism" : [],
                "Awareness Raising Events" : [],
            },
            "Speaking" : {
                "Manual Communication" : [],
                "Phone Skills" : [],
                "Speaking and Listening Skills" : [],
                "Speech Styles" : [],
                "Public Speaking" : [],
            },
            "Stationery" : {
                "Writing Implements" : [],
                "Binders Files and Folders" : [],
                "Paper Fasteners" : [],
                "Envelopes" : [],
                "Whiteboards" : [],
                "Basic Paper Skills" : [],
                "Pen and Pencil Crafts" : [],
                "Pencil Cases" : [],
                "Glue" : [],
            },
            "Subjects" : {
                "English" : [],
                "Geography" : [],
                "Mathematics" : [],
                "Law and Legislation" : [],
                "Reading and Comprehension Skills" : [],
                "History" : [],
                "Psychology Studies" : [],
                "Science" : [],
                "Studying Literature" : [],
                "Economics" : [],
                "Art Studies" : [],
            },
            "Teacher Resources" : {
                "Creating Lesson Plans" : [],
                "Classroom Management and Student Conduct" : [],
                "Teaching Students with Special Needs" : [],
                "Information Technology in the Classroom" : [],
            },
            "World Languages" : {
                "Spanish" : [],
                "Chinese" : [],
                "Japanese" : [],
                "German" : [],
                "Greek" : [],
                "Korean" : [],
                "Multiple Language Guides" : [],
                "English Dialects and Slang" : [],
                "French" : [],
                "Russian" : [],
                "Italian" : [],
                "Arabic" : [],
                "Hebrew" : [],
                "Dutch" : [],
                "Polish" : [],
                "Esperanto" : [],
                "Latin" : [],
                "Swedish" : [],
                "Urdu" : [],
                "Tagalog" : [],
                "Hawaiian" : [],
                "Turkish" : [],
                "Irish" : [],
                "Portuguese" : [],
                "Hindi" : [],
                "Norwegian" : [],
            },
            "Writing" : {
                "Diary and Secrets" : [],
                "Ideas and Inspiration" : [],
                "Official Writing and Complaints" : [],
                "Publishing" : [],
                "Works" : [],
                "Speechwriting" : [],
                "Letters" : [],
                "Journal Writing" : [],
                "Better Writing" : [],
                "Editing and Style" : [],
                "Technical Writing" : [],
                "Youth Writing" : [],
                "Article Writing" : [],
            },
        },
        "Family Life" : {
            "Creating Life Balance" : {
                "Dealing with Parents as an Adult" : [],
            },
            "Death Funerals and Bereavement" : {
                "Coping with Loss" : [],
            },
            "Family Reunions and Events" : {
            },
            "Family Traditions" : {
            },
            "Family Vacations" : {
            },
            "Genealogy" : {
            },
            "Grandparents" : {
            },
            "In Laws" : {
            },
            "Married Life" : {
                "Cheating Spouses" : [],
                "Wedding Anniversaries" : [],
                "Marriage Issues" : [],
                "Dealing with Separation and Divorce" : [],
                "Arranged Marriages" : [],
            },
            "Parenting" : {
                "Motherhood" : [],
                "Parenting and Technology" : [],
                "Nurturing Talent" : [],
                "Teaching Children Skills" : [],
                "Homeschooling" : [],
                "Development Stages" : [],
                "Adoption" : [],
                "Behavioral Issues" : [],
            },
            "Retirement" : {
                "Financing Retirement" : [],
            },
            "Weddings" : {
                "Wedding Planning" : [],
                "Honeymoons" : [],
                "Arranged Marriages" : [],
                "Engagement" : [],
                "Managing Wedding Stress" : [],
                "Wedding Anniversaries" : [],
                "Wedding Ceremonies" : [],
                "Wedding Clothes" : [],
                "Wedding Crafts" : [],
                "Wedding Decorating" : [],
                "Wedding Etiquette" : [],
                "Wedding Flowers" : [],
                "Wedding Gifts" : [],
                "Wedding Hair and Makeup" : [],
                "Wedding Memories" : [],
                "Wedding Music" : [],
                "Wedding Party" : [],
                "Wedding Photography" : [],
                "Wedding Receptions" : [],
                "Weddings by Nationality or Ethnicity" : [],
            },
        },
        "Finance and Business" : {
            "Auctions" : {
                "Auction Sites" : []
            },
            "Banks and Financial Institutions" : {
                "Banking and Finance Law" : [],
                "Checks and Checkbooks" : [],
                "Lending" : [],
                "Money Transfers" : [],
                "Online Banking" : [],
                "Opening a Bank Account" : [],
                "Payment Cards" : [],
                "Using Automated Teller Machines" : [],
                "Credit Rating" : [],
                "Personal Savings" : [],
                "Counterfeit Money" : []
            },
            "Business" : {
                "Customer Relations" : [],
                "Business by Industry" : [],
                "Business Personnel" : [],
                "Running a Business" : [],
                "Starting a Business" : [],
                "Business Skills" : [],
                "Business Promotion" : [],
                "Business Security" : [],
                "Business Communications and Information Technology" : []
            },
            "Finance Careers" : {
            },
            "Fundraising and Charity" : {
                "Crowdfunding" : [],
                "School Fundraising" : [],
                "Fundraising for Animals" : [],
                "Raffles" : [],
                "Donations" : []
            },
            "Government" : {
                "Citizenship and Immigration" : [],
                "Government Assistance" : [],
                "Social Security" : [],
                "Careers in Government" : [],
                "Political Campaigning and Participation" : [],
                "Political Occupations" : [],
                "Taxes" : []
            },
            "Investments and Trading" : {
                "Financial Stocks" : [],
                "Financial Bonds" : [],
                "Financial Ratios" : [],
                "Precious Metals Investment" : [],
                "Foreign Exchange Market" : [],
                "Mineral and Energy Investment" : [],
                "Investing in Real Estate" : []
            },
            "Legal Matters" : {
                "Retaining a Lawyer" : [],
                "Intellectual Property" : [],
                "Wills and Testaments" : [],
                "Contracts and Legal Agreements" : [],
                "Animals and the Law" : [],
                "Vehicles and the Law" : [],
                "Vital Records" : [],
                "Freedom of Information Processes" : [],
                "Family Law" : [],
                "Property Law" : [],
                "Consumer Protection Law" : [],
                "Employment Law" : [],
                "Health Law" : [],
                "Anti Discrimination Law" : [],
                "Sports Law" : [],
                "Tort Law" : [],
                "Malpractice and Misconduct" : [],
                "Court Practice and Procedure" : [],
                "Missing Persons" : [],
                "Communications Law" : [],
                "Public Law" : [],
                "Legal Careers" : [],
                "Law Enforcement" : [],
                "Banking and Finance Law" : [],
                "Corporate Law" : [],
                "Criminal Law" : [],
                "Alternative Dispute Resolution" : [],
                "Trust Law" : []
            },
            "Managing Your Money" : {
                "Budgeting" : [],
                "Recession" : [],
                "Making Money" : [],
                "Frugality" : [],
                "Personal Income" : [],
                "Wealth" : [],
                "Payment Cards" : [],
                "Managing Personal Debt" : [],
                "Financing Retirement" : [],
                "Personal Savings" : [],
                "Handling and Storing Money" : [],
                "Working with Financial Experts" : [],
                "Passive Income" : [],
                "Coins" : [],
                "Money Gifts" : [],
                "Counterfeit Money" : [],
                "Money Transfers" : []
            },
            "Marketing" : {
                "Advertising" : [],
                "Business Promotion" : [],
                "Ethical Consumerism" : [],
                "Hiring Marketing Experts" : [],
                "Marketing Careers" : [],
                "Marketing Materials" : [],
                "Marketing Plans and Strategies" : [],
                "Marketing Specific Products" : [],
                "Marketing Styles" : [],
                "Public Relations" : [],
                "Surveys" : []
            },
            "Mobile Payment Systems" : {
                "PayPal" : [],
                "Venmo" : [],
                "Apple Pay" : [],
                "Square App" : []
            },
            "Real Estate" : {
                "Renting" : [],
                "Selling Property" : [],
                "Buying Property" : [],
                "Property Loans and Mortgages" : [],
                "Commercial Real Estate" : [],
                "Investing in Real Estate" : [],
                "Property Law" : [],
                "Real Estate Businesses" : [],
                "Vacation Real Estate" : [],
                "Homelessness" : [],
                "Land Surveys" : []
            },
            "Risk Management" : {
                "Insurance" : []
            },
            "Sharing Economy" : {
                "Cryptocurrencies" : [],
                "Couchsurfing" : [],
                "Freecycling" : []
            },
            "Shopping" : {
                "Shopping Online" : [],
                "Ethical Consumerism" : [],
                "Sales and Bargain Shopping" : [],
                "Buying Goods by Type" : [],
                "Consumer Education" : [],
                "Dealing with Retailers and Salespeople" : [],
                "Shopping Cards and Vouchers" : [],
                "Returns Refunds and Exchanges" : [],
                "Retail Self Checkouts" : [],
                "Christmas Shopping" : []
            },
        },
        "Food and Entertaining" : {
            "Appreciation of Food" : {
                "Chocophilia": [],
                "Eating Techniques" : [],
            },
            "Barbecue" : {
                "Barbecue Equipment": [],
                "Barbecue Fish": [],
                "Barbecue Meat": [],
                "Smoked Meat": [],
                "Barbecue Fruits": [],
                "Barbecue Vegetables": [],
                "Burgers": [],
                "Coleslaw": [],
                "Grill Rubs" : [],
            },
            "Breakfast" : {
                "French Toast": [],
                "Pancakes": [],
                "Waffles": [],
                "Breakfast Cereal": [],
                "Toast": [],
                "Savory Breakfast Dishes": [],
                "Pop Tarts" : [],
            },
            "Care and Use of Cooking Equipment" : {
            },
            "Cooking Equipment" : {
                "Bakeware": [],
                "Cooking Knives and Blades": [],
                "Cookware": [],
                "Cutting Boards": [],
                "Kitchen Utensils": [],
                "Opening Food Containers" : [],
            },
            "Cooking for Children" : {
                "Baby Recipes": [],
                "Toddler Recipes": [],
                "Snacks for Kids" : [],
            },
            "Dining Etiquette" : {
            },
            "Dining Out" : {
                "Eating Out on a Budget" : [],
            },
            "Drinks" : {
                "Coffee": [],
                "Tea": [],
                "Water Ice and Sports Drinks": [],
                "Smoothies Shakes and Milk": [],
                "Chocolate and Cocoa Drinks": [],
                "Alcoholic Drinks": [],
                "Juice": [],
                "Sodas and Fizzy Drinks": [],
                "Citrus Based Drinks": [],
                "Mocktails": [],
                "Rose Drinks": [],
                "Holiday Drinks" : [],
            },
            "Food and Grocery Shopping" : {
                "Food and Grocery Budgeting" : [],
            },
            "Food Gifts" : {
            },
            "Food Preparation" : {
                "Meal Planning": [],
                "Food Selection and Storage": [],
                "Food Preservation Techniques": [],
                "Peeling Food": [],
                "Food Cutting Techniques": [],
                "Cleaning Food": [],
                "Basic Cooking Skills" : [],
            },
            "Food Safety" : {
            },
            "Herbs and Spices" : {
                "Spice Mixes": [],
                "Preserving Herbs": [],
                "Salt and Pepper": [],
                "Garlic": [],
                "Pesto": [],
                "Edible Flowers" : [],
            },
            "Holiday Cooking" : {
                "Thanksgiving Cooking": [],
                "Christmas Cooking": [],
                "Easter Cooking": [],
                "Valentine's Day Cooking": [],
                "New Year Cooking": [],
                "Islamic Holiday Cooking": [],
                "Jewish Holiday Cooking": [],
                "Fourth of July Food and Drink": [],
                "Saint Patrick's Day Cooking": [],
                "Cranberries": [],
                "Stuffings": [],
                "Chestnuts" : [],
            },
            "Nuts and Seeds" : {
                "Walnuts": [],
                "Chestnuts" : [],
            },
            "Parties" : {
                "Dinner Parties": [],
                "Party Snacks": [],
                "Theme Parties": [],
                "Party Games": [],
                "Parties for Children": [],
                "Party Planning": [],
                "Party Decorations": [],
                "Teen Parties": [],
                "Buffets": [],
                "Cocktail Parties": [],
                "Party Etiquette": [],
                "Parties for Animal Lovers and Pets": [],
                "Party Socializing": [],
                "Party Cleaning" : [],
            },
            "Picnics" : {
            },
            "Recipe Books and Cookbooks" : {
            },
            "Recipes" : {
                "Desserts and Sweets": [],
                "Fruits and Vegetables": [],
                "Meat": [],
                "Fish and Seafood": [],
                "Salads": [],
                "Jams Preserves and Condiments": [],
                "Pasta and Noodles": [],
                "Sandwiches and Quick Meals": [],
                "Soups": [],
                "Eggs and Dairy": [],
                "Rice and Beans": [],
                "Cereal Grains": [],
                "Chocolate and Candy": [],
                "World Cuisines": [],
                "Specialty Diet Recipes": [],
                "Vegetarian": [],
                "Baking": [],
                "Slow Cooker Recipes": [],
                "Pressure Cooker Recipes" : [],
            },
        },
        "Health" : {
            "Alternative Health" : {
                "Breathing and Meditation" : [],
                "Relaxation Techniques" : [],
                "Yoga" : [],
                "Home Remedies" : [],
                "Hypnosis" : [],
                "Reiki" : [],
                "Acupuncture" : [],
                "Chakras" : [],
                "Crystal Healing" : [],
                "Essential Oils" : [],
                "Homeopathy" : [],
                "Reflexology" : [],
            },
            "Cancer" : {
                "Breast Cancer" : [],
                "Cervical Cancer" : [],
                "Chemotherapy" : [],
                "Children and Cancer" : [],
                "Colon Cancer" : [],
                "Lung Cancer" : [],
                "Ovarian Cancer" : [],
                "Prostate Cancer" : [],
                "Skin Cancer" : [],
                "Supporting Cancer Patients" : [],
                "Blood Cancers" : [],
                "Preventing Cancer" : [],
            },
            "Cardiovascular System Health" : {
                "Angina" : [],
                "Artery Health" : [],
                "Blood Health" : [],
                "Cholesterol and Lipoproteins" : [],
                "Eating for Heart Health" : [],
                "Fainting (Syncope)" : [],
                "Heart Attacks (Myocardial Infarction)" : [],
                "Pulse Rate" : [],
                "Strokes" : [],
                "Vein Health" : [],
                "Cardiac Arrest" : [],
                "Cardio Exercises" : [],
                "Defibrillation" : [],
                "Heart Arrhythmia (Irregular Heartbeat)" : [],
                "Heart Disease" : [],
                "Heart Failure" : [],
            },
            "Childhood Health" : {
                "Childhood Fears and Phobias" : [],
            },
            "Coping with Illness" : {
                "Being a Patient" : [],
                "Caregiving" : [],
                "Chronic Illness" : [],
                "Pain Management" : [],
                "Recovery from Illness" : [],
                "Sleep Affected by Illness or Pain" : [],
                "Talking to Your Doctor" : [],
                "Visiting Hospital and Patients" : [],
                "End of Life Care" : [],
            },
            "Diet & Lifestyle" : {
                "Vegetarian Health" : [],
                "Eating Disorders" : [],
                "Nutrition and Lifestyle Eating" : [],
                "Food Addictions and Cravings" : [],
                "Maintaining Diets" : [],
                "Losing Weight" : [],
            },
            "Digestive System Health" : {
                "Foodborne Illnesses (Food Poisoning)" : [],
                "Gastrointestinal Tract Health" : [],
                "Gallbladder Health" : [],
                "Hernias" : [],
                "Liver Health" : [],
                "Nausea and Vomiting" : [],
                "Pancreas Health" : [],
                "Tongue Health" : [],
            },
            "Disability Issues" : {
                "Attention and Developmental Disorders" : [],
                "Disability Forms Permits and Benefits" : [],
                "Blind and Visually Impaired" : [],
                "Deaf and Hard of Hearing" : [],
                "Autism Spectrum" : [],
                "Down Syndrome" : [],
                "Dyslexia" : [],
                "Mobility Disabilities" : [],
            },
            "Ear Health" : {
                "Ear Infections" : [],
                "Ear Pain" : [],
                "Hearing Loss" : [],
                "Hearing Aids" : [],
                "Tinnitus" : [],
                "Noise and Health" : [],
                "Vestibular System (Sense of Balance)" : [],
                "Cleaning Ears" : [],
            },
            "Emotional Health" : {
                "Emotional Conditions" : [],
                "Assertiveness & Self Esteem" : [],
                "Overcoming Shyness & Insecurities" : [],
                "Happiness & Optimism" : [],
                "Managing Negative Feelings" : [],
                "Stress Anxiety and Crisis Management" : [],
                "Personal Development" : [],
                "Abuse" : [],
                "Addictions" : [],
            },
            "Endocrine System Health" : {
                "Endocrine Disorders" : [],
                "Hormones" : [],
                "Hormone Replacement Therapy" : [],
                "Kidney Health" : [],
                "Menopause" : [],
                "Pancreas Health" : [],
                "Pituitary Gland Health" : [],
                "Thyroid Gland Health" : [],
            },
            "Environmental Health" : {
                "Air Quality and Health" : [],
                "Avoiding Harmful Personal Care Ingredients" : [],
                "Disorders and Illnesses of Unknown Cause" : [],
                "Health and Mold Exposure" : [],
                "Noise and Health" : [],
                "Occupational Diseases" : [],
                "Radiological Health" : [],
                "Safe Drinking Water" : [],
                "Sun Safety" : [],
                "Thermoregulation" : [],
                "Toxic Chemical Exposure" : [],
            },
            "Eye Health" : {
                "Corneal Health" : [],
                "Eye Disorders" : [],
                "Eye Health for Older Adults" : [],
                "Eye Skin Conditions (Circles and Puffiness)" : [],
                "Eye Surgery" : [],
                "First Aid for Eyes" : [],
                "Vision" : [],
                "Eye Exercises" : [],
            },
            "First Aid and Emergency Health Care" : {
                "Allergy Emergencies" : [],
                "Asthma Emergencies" : [],
                "Baby First Aid" : [],
                "Bites and Stings" : [],
                "Bleeding and Shock" : [],
                "Burns and Scalds" : [],
                "Childbirth Emergencies" : [],
                "Choking First Aid" : [],
                "Diabetic Emergencies" : [],
                "Disturbed Behavior Emergency Response" : [],
                "Drowning" : [],
                "Drug Overdoses" : [],
                "Epidemics" : [],
                "Fainting (Syncope)" : [],
                "Fever Care" : [],
                "First Aid for Eyes" : [],
                "First Aid for Traffic Accident Injuries" : [],
                "First Aid Hygiene" : [],
                "First Aid Kits" : [],
                "Gastrointestinal Emergencies" : [],
                "Heart Attacks (Myocardial Infarction)" : [],
                "Heat and Cold Injuries" : [],
                "Meningitis" : [],
                "Poisoning" : [],
                "Resuscitation (CPR)" : [],
                "Seizures and Febrile Convulsions" : [],
                "Soft Tissue Injuries" : [],
                "Spinal Injuries" : [],
                "Strokes" : [],
                "Wound First Aid" : [],
                "Panic Attacks" : [],
                "Head Injuries" : [],
                "Cardiac Arrest" : [],
                "Wilderness First Aid" : [],
                "Bone Fractures" : [],
                "First Aid Carrying" : [],
                "Foreign Objects First Aid" : [],
            },
            "Genetic Health" : {
            },
            "Health Care and Medical Information" : {
                "Finding a Medical Specialist" : [],
            },
            "Health Hygiene" : {
            },
            "Healthy Aging and Senior Lifestyle" : {
                "Aged Care" : [],
                "Energy & Longevity" : [],
            },
            "Immune System Health" : {
                "Allergies" : [],
                "Autoimmune Diseases" : [],
                "Immunization and Vaccinations" : [],
                "Inflammation" : [],
                "Mold Exposure and Health" : [],
                "Tonsils Health" : [],
                "Food Hypersensitivities" : [],
                "Organ Transplantation" : [],
            },
            "Infectious Diseases" : {
                "Fever Care" : [],
                "Meningitis" : [],
                "Animal to Human Infections (Zoonoses)" : [],
                "Bacterial Infections" : [],
                "Epidemics" : [],
                "Foodborne Illnesses (Food Poisoning)" : [],
                "Fungal Infections" : [],
                "Viral Infections" : [],
                "Sexually Transmitted Diseases" : [],
                "Pneumonia" : [],
                "Preventing Spread of Infection" : [],
            },
            "Integumentary System Health" : {
                "Avoiding Harmful Personal Care Ingredients" : [],
                "Nail Health" : [],
                "Perspiration (Sweating)" : [],
                "Scalp Health" : [],
                "Skin Health" : [],
                "Hair Health" : [],
            },
            "Lymphatic System Health" : {
                "Edema" : [],
                "Tonsils Health" : [],
            },
            "Medication and Medical Equipment" : {
                "Hot and Cold Compresses" : [],
                "Injections" : [],
                "Taking Pills and Medicine" : [],
            },
            "Men's Health" : {
                "Male Pattern Hair Loss" : [],
            },
            "Musculoskeletal System Health" : {
                "Arm and Hand Health" : [],
                "Arthritis" : [],
                "Back and Spine Health" : [],
                "Bone Health" : [],
                "Leg and Foot Health" : [],
                "Musculoskeletal Pain" : [],
                "Neck and Shoulder Health" : [],
                "Posture" : [],
                "Soft Tissue Injuries" : [],
            },
            "Nervous System Health" : {
                "Brain Damage (Brain Injury)" : [],
                "Dementia" : [],
                "Headaches" : [],
                "Head Injuries" : [],
                "Movement Disorders" : [],
                "Multiple Sclerosis" : [],
                "Pain Management" : [],
                "Peripheral Nervous System Disorders (Nerves)" : [],
                "Seizures and Febrile Convulsions" : [],
                "Sensory Nervous System Health" : [],
                "Sleep Disorders" : [],
                "Spine Disorders" : [],
                "Strokes" : [],
                "Brain Tumors" : [],
            },
            "Recreational Drug Use" : {
                "Smoking Addictions" : [],
                "Drug Addictions" : [],
                "Smoking" : [],
                "Smoking and Health Effects" : [],
            },
            "Reproductive Health" : {
                "Birth Control and Contraceptives" : [],
                "Sexually Transmitted Diseases" : [],
            },
            "Respiratory System Health" : {
                "Asthma" : [],
                "Breathing Health" : [],
                "Chest Health" : [],
                "Common Cold" : [],
                "Chronic Obstructive Pulmonary Disease (COPD)" : [],
                "Cystic Fibrosis" : [],
                "Influenza (Flu)" : [],
                "Lung Health" : [],
                "Nose Health" : [],
                "Oxygen Administration" : [],
                "Pneumonia" : [],
                "Sinus Health" : [],
                "Thoracic Diaphragm Health" : [],
                "Throat Health" : [],
                "Larynx (Voice Box) Health" : [],
            },
            "Sleep and Dreams" : {
                "Dreams" : [],
                "Sleep Disorders" : [],
                "Better Sleeping" : [],
            },
            "Sports Health" : {
                "Sports and Pain Management" : [],
                "Soft Tissue Injuries" : [],
                "Cooling Down (Sports)" : [],
                "Warming Up (Sports)" : [],
                "Menstruation and Sports" : [],
                "Exercising During Pregnancy" : [],
            },
            "Surgery" : {
                "Bariatric Surgery (Weight Loss Surgery)" : [],
                "Eye Surgery" : [],
                "Hip Replacement Surgery" : [],
                "Plastic and Cosmetic Surgery" : [],
                "Recovery from Surgery" : [],
                "Surgical Sutures (Stitches)" : [],
                "Organ Transplantation" : [],
                "Hair Transplant Surgery" : [],
                "Breast Surgery" : [],
                "Caesarean Section" : [],
            },
            "Teeth and Mouth Health" : {
                "Gum Health" : [],
                "Jaw Health" : [],
                "Lip Health" : [],
                "Mouth Disorders" : [],
                "Oral Hygiene" : [],
                "Periodontal Diseases" : [],
                "Tooth Health" : [],
                "Tongue Health" : [],
            },
            "Travel Health" : {
                "Air Travel Health" : [],
            },
            "Urinary System Health" : {
                "Bladder Health" : [],
                "Kidney Health" : [],
                "Urinary Incontinence" : [],
                "Urinary Tract Infections" : [],
                "Urination" : [],
                "Urological Catheters" : [],
            },
            "Women’s Health" : {
                "Breast Health" : [],
                "Menopause" : [],
                "Candida Infections" : [],
                "Ovarian Health" : [],
                "Pelvic Inflammatory Disease" : [],
                "Vaginal Health" : [],
                "Cervical Health" : [],
                "Female Pattern Hair Loss" : [],
                "Menstruation" : [],
                "Uterine Health" : [],
                "Obstetrics" : [],
            },
        },
        "Hobbies and Crafts" : {
            "Amateur Radio" : {
            },
            "Astronomy" : {
                "Telescopes" : [],
                "Astronomical Charts" : [],
                "Astronomy Models" : [],
                "Meteor Showers" : [],
                "Moon Watching" : [],
                "Planet Watching" : [],
            },
            "Boredom Busters" : {
                "Enjoying Boredom" : [],
                "Seasonal and Holiday Boredom" : [],
                "Beating Home Boredom" : [],
            },
            "Collecting" : {
                "Stamp Collecting" : [],
                "Vintage Sewing and Textiles" : [],
                "Coins" : [],
                "Rock Gem Mineral and Fossil Collecting" : [],
                "Collecting Cards and Postcards" : [],
                "Collectible Models and Toys" : [],
                "Snow Globes" : [],
                "Art Collection" : [],
                "Antiques" : [],
                "Beach and Ocean Collectibles" : [],
                "Beverage Collectibles" : [],
                "Collecting Books" : [],
                "Displaying Collections" : [],
                "Fashion Collectibles" : [],
                "Gaming Collectibles" : [],
                "Kitchen Collectibles" : [],
                "Movie Collections" : [],
                "Music Collectibles" : [],
                "Paper Collectibles" : [],
                "Sports Collectibles" : [],
                "Stationery Collectibles" : [],
                "Valuing Collectibles" : [],
                "Auctions" : [],
            },
            "Crafts" : {
                "Clay Projects" : [],
                "Beading" : [],
                "Sewing" : [],
                "Selling Arts and Crafts" : [],
                "Glass and Stained Glass Projects" : [],
                "Basketry Wicker and Rattan" : [],
                "Nature Crafts" : [],
                "Metalwork and Wire Projects" : [],
                "Candle Making" : [],
                "Soap Making" : [],
                "Flower Arranging and Floral Art" : [],
                "Plastic and Adhesive Projects" : [],
                "Decoration Projects" : [],
                "Paper Craft" : [],
                "Felt Projects" : [],
                "Leatherworking" : [],
                "Yarn and Thread" : [],
                "Animal Art and Craft" : [],
                "Craft for Kids" : [],
                "Printing Crafts" : [],
                "Making Personal Accessories" : [],
                "Jewelry Making" : [],
                "Creative Reuse and Repurposing" : [],
                "Hatmaking (Millinery)" : [],
                "Needlework" : [],
                "Craft Painting" : [],
                "Wooden Craft Projects" : [],
                "Craft and Photography" : [],
                "Studios" : [],
            },
            "Digital Technology Art and Craft Projects" : {
                "Robots" : [],
                "Paper Crafts for Electronic Items" : [],
                "Making Multimedia Bags and Covers" : [],
            },
            "Drawing" : {
                "Drawing Shapes and Forms" : [],
                "Drawing People and Features" : [],
                "Drawing Flowers and Plants" : [],
                "Fantasy Drawing" : [],
                "Coloring and Shading" : [],
                "Accessories for Drawing" : [],
                "Improving Drawing Skills" : [],
                "Tracing and Copying Drawing" : [],
                "Drawing Household Objects" : [],
                "Drawing Therapy" : [],
                "Drawing Animals" : [],
                "Drawing Text and Lettering" : [],
                "Drawing Food and Drinks" : [],
                "Drawing Sports Equipment" : [],
                "Drawing Weaponry" : [],
                "Drawing Celebrities and Characters" : [],
                "Drawing Vehicles" : [],
                "Drawing Geography" : [],
                "Drawing Games" : [],
            },
            "Fireworks" : {
                "Bombs" : [],
            },
            "Flags" : {
                "Hanging Flags" : [],
                "Making Flags" : [],
            },
            "Games" : {
                "Backyard Games" : [],
                "Darts" : [],
                "Puzzles and Memory Games" : [],
                "Party Games" : [],
                "Games of Imagination" : [],
                "Scary Games" : [],
                "Paper Games" : [],
                "Role Playing Games" : [],
                "String Games" : [],
                "Games of Chance" : [],
                "Card Games" : [],
                "Board Games" : [],
                "Spying" : [],
                "Creating Games" : [],
                "Wargaming" : [],
                "Playground Games" : [],
            },
            "Inventions" : {
                "Patents" : [],
                "Product Launches" : [],
            },
            "Kite Making and Kite Flying" : {
            },
            "Knot Tying" : {
            },
            "Model Making" : {
                "Painting Miniatures" : [],
                "Model Rockets" : [],
                "Model Aircraft" : [],
                "Dioramas" : [],
                "Craft Stick Projects" : [],
                "Astronomy Models" : [],
                "Biology Models" : [],
                "Bridge Models" : [],
                "Miniature Food" : [],
                "Model Boats and Ships" : [],
                "Model Cars and Trucks" : [],
                "Model Castles" : [],
                "Model Rail and Trains" : [],
                "Town and City Models" : [],
                "Model Buildings" : [],
                "Terrain and Landscape Models" : [],
                "Wargaming Miniatures" : [],
            },
            "Optical Devices" : {
                "Binoculars" : [],
                "Microscopes" : [],
                "Telescopes" : [],
            },
            "Painting" : {
                "Artist Inspired Painting" : [],
                "Art Equipment" : [],
                "Craft Painting" : [],
                "House Painting" : [],
                "Painting Furniture" : [],
                "Painting Media" : [],
                "Painting Projects for Kids" : [],
                "Painting Subjects" : [],
                "Paints" : [],
            },
            "Photography" : {
                "Digital Photography" : [],
                "Nature and Outdoor Photography" : [],
                "Photography Lighting" : [],
                "Slideshows" : [],
                "Film Cameras and Film Photography" : [],
                "Photo Albums" : [],
                "Three Dimensional Photography" : [],
                "People and Portrait Photography" : [],
                "Sports Photography" : [],
                "Blog Photography Tips" : [],
                "Craft and Photography" : [],
                "Improving Photos" : [],
                "Macro Photography" : [],
                "Photographic DIY" : [],
                "Displaying Photos" : [],
            },
            "Rocks and Minerals" : {
                "Cleaning Gemstones and Minerals" : [],
                "Cleaning Stone" : [],
                "Geodes" : [],
                "Geology" : [],
                "Gemstones" : [],
                "Fossils" : [],
                "Identifying Rocks and Minerals" : [],
                "Mineral and Energy Investment" : [],
                "Mineral Rights" : [],
                "Rock Gem Mineral and Fossil Collecting" : [],
                "Metals" : [],
            },
            "Sculpting" : {
                "Foam and Sponge Projects" : [],
                "Stone Sculpting" : [],
            },
            "Toys" : {
                "Remote Control Toys" : [],
                "Designing Creative Play Games" : [],
                "Toy Pets" : [],
                "Action Toys" : [],
                "Traditional Toys" : [],
                "Construction Toys" : [],
                "Care and Repair of Toys" : [],
                "Toy Figurines and Accessories" : [],
                "Dolls and Doll Houses" : [],
                "Baby Toys" : [],
                "Toy Hammocks" : [],
                "Making Plastic Toys" : [],
            },
            "Tricks and Pranks" : {
                "Body Tricks" : [],
                "Tricks with Objects" : [],
                "Jokes" : [],
                "Magic Tricks" : [],
                "Juggling" : [],
                "Pranks and Gags" : [],
                "Card Tricks" : [],
            },
            "Woodworking" : {
                "Wooden Toys and Puzzle Making" : [],
                "Wooden Craft Projects" : [],
                "Wood Finishes and Treatments" : [],
                "Woodworking Tools" : [],
                "Birdhouses" : [],
                "Wooden Sports Equipment" : [],
                "Painting Wood" : [],
                "Building Workbenches" : [],
                "Building Furniture" : [],
                "Making Doors" : [],
                "Pallet Projects" : [],
                "Wood" : [],
                "Wooden Transportation Projects" : [],
            },
        },
        "Holidays and Traditions" : {
            "April Fool's Day" : {
            },
            "Awareness Raising Events" : {
                "Animal Awareness Events" : [],
                "Environmental Awareness Events" : [],
                "Food Awareness Events" : [],
                "Literary and Literacy Awareness Events" : [],
                "Science Awareness Events" : [],
            },
            "Birthdays" : {
                "Birthday Cards" : [],
                "Milestone Birthday Celebrations" : [],
                "Birthday Cakes" : [],
                "Birthday Gifts" : [],
                "Birthday Music" : [],
                "Birthday Outings" : [],
                "Birthday Parties" : [],
                "Birthday Reminders" : [],
                "Decorating for Birthdays" : [],
                "Family Birthdays" : [],
                "Famous Birthdays" : [],
                "Happy Birthday in Other Languages" : [],
            },
            "Celebration Events" : {
                "Celebration Events for Children" : [],
                "Family Celebration Events" : [],
                "Quirky Celebration Events" : [],
                "Seasonal Celebration Events" : [],
            },
            "Christian Special Days" : {
                "Faith at Christmas" : [],
                "Faith at Easter" : [],
                "Mardi Gras" : [],
            },
            "Christmas" : {
                "Christmas Trees" : [],
                "Christmas Gifts" : [],
                "Christmas Spirit" : [],
                "Christmas for Kids" : [],
                "Christmas Parties" : [],
                "Christmas Lighting" : [],
                "Christmas at the Workplace" : [],
                "Christmas Celebrations by Country" : [],
                "Christmas Cooking" : [],
                "Christmas Crafts" : [],
                "Christmas Fashion" : [],
                "Christmas Music" : [],
                "Christmas Organization" : [],
                "Christmas Themes" : [],
                "Christmas Writing Projects" : [],
                "Decorating for Christmas" : [],
                "Managing Holiday Season Stress" : [],
                "Pets and Christmas" : [],
            },
            "Day of the Dead" : {
            },
            "Easter" : {
                "Easter Crafts" : [],
                "Decorating for Easter" : [],
                "Easter Bunny" : [],
                "Easter Celebrations by Country" : [],
                "Easter Cooking" : [],
                "Easter Egg Hunts" : [],
                "Easter Parties" : [],
                "Faith at Easter" : [],
            },
            "Festivals" : {
                "Music Festivals" : [],
            },
            "Gift Giving" : {
                "Gift Wrapping" : [],
                "Gift Baskets" : [],
                "Christmas Gifts" : [],
                "Budget Gifts" : [],
                "Donations" : [],
                "Family Gifts" : [],
                "Gifts by Person" : [],
                "Gifts by Type" : [],
                "Making Gifts" : [],
                "Sending Gifts" : [],
                "Special Occasion Gifts" : [],
                "Surprise Gifts" : [],
                "Unwanted Gifts" : [],
                "White Elephant Gift Exchange" : [],
            },
            "Halloween" : {
                "Halloween Costumes" : [],
                "Halloween Parties" : [],
                "Halloween Pumpkins" : [],
                "Halloween Decorations" : [],
                "Halloween Pranks" : [],
                "Halloween Food" : [],
                "Halloween Crafts" : [],
                "Halloween Drinks" : [],
                "Halloween Safety" : [],
                "Halloween Trick or Treating" : [],
            },
            "Hindu Holy Days and Festivals" : {
                "Diwali" : [],
            },
            "Holiday Season" : {
                "Celebrating Holidays Mindfully" : [],
                "Holiday Cooking" : [],
                "Holiday Crafts" : [],
                "Holiday Drinks" : [],
                "Holiday Parties" : [],
                "Holiday Season Safety" : [],
                "Managing Holiday Season Stress" : [],
            },
            "Islamic Holy Days and Periods" : {
                "Islamic Holiday Cooking" : [],
                "Ramadan" : [],
            },
            "Jewish Holy Days" : {
                "Hanukkah Chanukah" : [],
                "Jewish Holiday Cooking" : [],
                "Passover" : [],
            },
            "Kwanzaa" : {
            },
            "Mardi Gras" : {
            },
            "National Days" : {
                "National Days (Australia and New Zealand)" : [],
                "National Days (USA)" : [],
            },
            "New Year" : {
                "Chinese New Year" : [],
                "New Year Cooking" : [],
                "New Year's Eve" : [],
                "New Year Resolutions" : [],
            },
            "Saint Patrick's Day" : {
                "Saint Patrick's Day Cooking" : [],
                "Saint Patrick's Day Crafts" : [],
            },
            "Superstitions" : {
            },
            "Thanksgiving" : {
                "Decorating for Thanksgiving" : [],
                "Faith at Thanksgiving" : [],
                "Thanksgiving Cooking" : [],
                "Thanksgiving Crafts" : [],
            },
            "Traditional Chinese Holidays" : {
                "Chinese New Year" : [],
            },
            "Travel and Traditional Celebrations" : {
            },
            "Vacation Time" : {
                "Family Vacations" : [],
                "Staycations" : [],
            },
            "Valentine's Day" : {
                "Valentine's Day Cooking" : [],
                "Valentine's Day Crafts" : [],
                "Romantic Cards" : [],
                "Valentine's Day for Singles" : [],
                "Valentine's Day Flowers" : [],
                "Valentine's Day Gifts" : [],
                "Valentine's Day Parties" : [],
                "Decorating for Valentine's Day" : [],
                "Valentine's Day Dating" : [],
            },
            "War Remembrance Days" : {
                "Cinco de Mayo" : [],
                "Floral Wreaths" : [],
            },
        },
        "Home and Garden" : {
            "Apartment Living" : {
                "Apartment Cleaning" : [],
                "Apartment Gardening" : [],
                "Apartment Living with Children" : [],
                "Apartment Rentals" : [],
                "Buying Apartments" : [],
                "Campus Apartments" : [],
                "Decorating Apartments" : [],
                "Moving Apartments" : [],
                "Pets in Apartments" : [],
                "Selling Apartments" : [],
            },
            "Disaster Preparedness" : {
                "Home Security" : [],
                "Storms" : [],
                "Fire Emergencies" : [],
                "Hazard Survival Equipment" : [],
                "Earthquakes and Tsunamis" : [],
                "Floods" : [],
                "Animals in Emergencies" : [],
                "Radiological Disasters and Threats" : [],
                "Safe Drinking Water" : [],
            },
            "DIY" : {
                "Brickwork and Stone Masonry" : [],
                "Caulking" : [],
                "Concrete" : [],
                "House Painting" : [],
                "Metalworking" : [],
                "Plastic" : [],
                "Plumbing" : [],
                "Tiles and Tiling" : [],
            },
            "Furniture" : {
                "Baby Furniture" : [],
                "Bedroom Furniture" : [],
                "Building Furniture" : [],
                "Buying Furniture" : [],
                "Cabinets and Cupboards" : [],
                "Chairs and Seating" : [],
                "Countertops and Kitchen Benches" : [],
                "Desks" : [],
                "Dining Room Furniture" : [],
                "Furniture Arrangement" : [],
                "Furniture Care" : [],
                "Furniture Fixes" : [],
                "Furniture Finishes" : [],
                "Furniture for Children" : [],
                "Moving Furniture" : [],
                "Office Furniture" : [],
                "Outdoor Furniture" : [],
                "Ready to Assemble Furniture" : [],
                "Selling Furniture" : [],
                "Shelves" : [],
                "Tables" : [],
                "Upholstery" : [],
            },
            "Garages" : {
                "Garage Floors" : [],
                "Garage Doors" : [],
                "Building Garages" : [],
                "Building Workbenches" : [],
                "Garage and Yard Sales" : [],
                "Garage Storage" : [],
            },
            "Gardening" : {
                "Compost Mulch and Soil Preparation" : [],
                "Garden Pests and Weeds" : [],
                "Harvest and Storage" : [],
                "Indoor and Patio Plants" : [],
                "Planting and Growing" : [],
                "Theme and Feature Gardens" : [],
                "Hydroponics" : [],
                "Creating Habitats for Wildlife" : [],
                "Gardening Tools" : [],
                "Garden Crafts" : [],
                "Garden Projects" : [],
                "Cleaning Up Garden" : [],
                "Landscaping Plants" : [],
                "Garden Sheds" : [],
            },
            "Heating and Cooling" : {
                "Air Conditioning" : [],
                "Cooling Systems" : [],
                "Efficient Energy Use" : [],
                "Energy Suppliers" : [],
                "Fans and Ventilation" : [],
                "Fire" : [],
                "Heating Systems" : [],
                "Insulation" : [],
                "Moisture Protection and Prevention" : [],
                "Renewable Energy" : [],
                "Winterization" : [],
            },
            "Home Appliances" : {
                "Cleaning Home Appliances" : [],
                "Floor Care Appliances" : [],
                "Heater Appliances" : [],
                "Humidity Appliances" : [],
                "Kitchen Appliances" : [],
                "Painting Household Appliances" : [],
                "Washing Machines and Dryers" : [],
            },
            "Home Decorating" : {
                "Budget Decorating" : [],
                "Decorating with Prints and Pictures" : [],
                "Feng Shui Decorating" : [],
                "Using Light for Interior Design" : [],
                "Interior Design for Rooms" : [],
                "Renter Friendly Decorating Ideas" : [],
                "Home Decor" : [],
                "Country Interior Design" : [],
                "Furniture Arrangement" : [],
                "Hiring Interior Designers" : [],
                "Hanging Things" : [],
                "Home Libraries" : [],
                "Interior Design and Colors" : [],
                "Minimalist Interior Design" : [],
                "Seasonal Interior Design" : [],
                "Small Space Interior Design" : [],
                "Table Decorations" : [],
                "Vintage Interior Design" : [],
            },
            "Home Gyms" : {
            },
            "Home Improvements" : {
                "Bathroom Remodel and Renovation" : [],
                "Flipping Houses" : [],
                "House Building" : [],
                "Kitchen Remodel and Renovation" : [],
                "Renovation Advice and Tips" : [],
                "Sustainable Houses" : [],
            },
            "Home Maintenance" : {
                "Roofs" : [],
                "Attics and Lofts" : [],
                "Basements and Cellars" : [],
                "Bathrooms" : [],
                "Bedrooms" : [],
                "Dining Rooms" : [],
                "Doors and Windows" : [],
                "Electrical Maintenance" : [],
                "Entrances and Hallways" : [],
                "Floors and Stairs" : [],
                "Home Repairs" : [],
                "Home Sanctuaries" : [],
                "House Foundations" : [],
                "House Painting" : [],
                "Kitchens" : [],
                "Laundry Rooms" : [],
                "Living Rooms" : [],
                "Playrooms" : [],
                "Plumbing" : [],
                "Studios" : [],
                "Study Rooms" : [],
                "Sunrooms" : [],
                "Walls and Ceilings" : [],
            },
            "Home Security" : {
                "Locks and Keys" : [],
                "Alarms" : [],
                "Baby Monitors" : [],
                "Budget Home Security" : [],
                "Door Security" : [],
                "Hiding Things" : [],
                "Home Intruders" : [],
                "House Security While Away" : [],
                "Security Systems" : [],
                "Theft" : [],
                "Training Watchdogs and Guard Dogs" : [],
            },
            "Housekeeping" : {
                "Pest Control" : [],
                "Cleaning" : [],
                "Tableware" : [],
                "House Guests" : [],
                "Laundry" : [],
                "Stain Removal" : [],
                "Indoor Air Improvement" : [],
                "Household Waste Disposal" : [],
                "Home Organization" : [],
                "Housekeeping Tools" : [],
                "Hired Home Help" : [],
                "Seasonal Housekeeping" : [],
                "Mold and Mildew Treatment" : [],
                "Frugality" : [],
            },
            "Lighting" : {
                "Candles" : [],
                "Car Lighting" : [],
                "Chandeliers" : [],
                "Christmas Lighting" : [],
                "Ceiling Lights" : [],
                "Closet and Cabinet Lights" : [],
                "Energy Saving Lighting" : [],
                "Flashlights" : [],
                "Glow Sticks" : [],
                "Hanging Lights" : [],
                "Lamps and Lampshades" : [],
                "Lanterns" : [],
                "LED Lighting" : [],
                "Light Bulbs" : [],
                "Light Switches" : [],
                "Motion Sensor Lighting" : [],
                "Night Lights" : [],
                "Outdoor Lights" : [],
                "Photography Lighting" : [],
                "Recessed Lighting" : [],
                "Rope Lights" : [],
                "Skylights" : [],
                "Using Light for Interior Design" : [],
                "Fluorescent Lights" : [],
                "Cleaning Lights" : [],
            },
            "Moving and Removals" : {
                "Cargo" : [],
                "Changing Address" : [],
                "Coping with New Places" : [],
                "Housewarming" : [],
                "Moving Apartments" : [],
                "Moving Cross Country" : [],
                "Moving House" : [],
                "Moving Internationally" : [],
                "Moving Out Cleaning" : [],
                "Moving Stress" : [],
                "Moving to the City" : [],
                "Moving with Pets" : [],
                "Planning to Move" : [],
                "Storage" : [],
            },
            "Sustainable Living" : {
                "Renewable Energy" : [],
                "Efficient Energy Use" : [],
                "Community Gardening and Urban Agriculture" : [],
                "Sustainable and Green Businesses" : [],
                "Frugality" : [],
                "Green Cleaning" : [],
                "Sustainable Houses" : [],
                "Minimalist Lifestyle" : [],
            },
            "Swimming Pools" : {
                "Above Ground Pools" : [],
                "Hot Tubs" : [],
                "Saunas" : [],
                "Swimming Pool Cleaning" : [],
                "Swimming Pool Equipment" : [],
                "Swimming Pool Maintenance" : [],
                "Swimming Pool Water Treatment" : [],
            },
            "Tools" : {
                "Locks and Keys" : [],
                "Gardening Tools" : [],
                "Woodworking Tools" : [],
                "Fastening Tools" : [],
                "Cutting Tools" : [],
                "Hole Making Tools" : [],
                "Measuring and Marking Tools" : [],
                "Shaping Tools" : [],
                "Tool Organization" : [],
                "Industrial Machinery and Tools" : [],
                "Holding and Support Tools" : [],
                "Automotive Tools" : [],
                "Housekeeping Tools" : [],
            },
            "Yard and Outdoors" : {
                "Decks" : [],
                "Docks and Piers" : [],
                "Earthworks" : [],
                "Fences and Gates" : [],
                "Landscaping" : [],
                "Lawn Care" : [],
                "Mailboxes" : [],
                "Outdoor and Retaining Walls" : [],
                "Outdoor Buildings" : [],
                "Outdoor Living Spaces" : [],
                "Outdoor Painting" : [],
                "Outdoor Play Equipment" : [],
                "Outdoor Shelters" : [],
                "Outdoor Water Features" : [],
                "Paths and Paving" : [],
                "Siding" : [],
                "Tree Services" : [],
                "Water Conservation" : [],
            },
        },
        "Personal Care and Style" : {
            "Beauty Contests and Beauty Pageants" : {
            },
            "Fashion" : {
                "Accessories and Handbags" : [],
                "Fashion Fixes" : [],
                "Plus Size Fashion" : [],
                "Creating Fashion Wardrobes" : [],
                "Body Type and Fashion" : [],
                "Color in Fashion" : [],
                "Shopping for Clothes" : [],
                "Seasonal Fashion" : [],
                "Fashion Design and Fashion Shows" : [],
                "Fashion Styles" : [],
                "Clothes by Type" : [],
                "Looking Good with Glasses" : [],
                "Christmas Fashion" : [],
                "New Year's Eve Fashion" : [],
            },
            "Grooming" : {
                "Looking Good & Makeovers" : [],
                "Perfume and Body Fragrances" : [],
                "Makeup" : [],
                "Handmade Cosmetics" : [],
                "Skin Care" : [],
                "Hair Care" : [],
                "Hand and Foot Care" : [],
            },
            "Jewelry" : {
                "Authenticating Jewelry" : [],
                "Bracelets and Bangles" : [],
                "Brooches and Pins" : [],
                "Buying Jewelry" : [],
                "Earrings" : [],
                "Gold Jewelry" : [],
                "Jewelry Care" : [],
                "Jewelry Gifts" : [],
                "Jewelry Making" : [],
                "Necklaces" : [],
                "Pearls" : [],
                "Rings" : [],
                "Selling Jewelry" : [],
                "Silver Jewelry" : [],
                "Watches" : [],
            },
            "Personal Hygiene" : {
                "Bathing" : [],
                "Feminine Hygiene" : [],
                "Hair Removal" : [],
                "Hand Hygiene" : [],
                "Deodorant" : [],
                "Body Odor" : [],
                "Cleaning Paint Off Skin" : [],
            },
            "Personality Traits and Attributes" : {
            },
            "Self Defense" : {
            },
            "Spa Treatments & Massages" : {
                "Massage Oils and Lotions" : [],
            },
            "Tattoos and Piercing" : {
                "Temporary Tattoos" : [],
                "Fake Piercing" : [],
                "Ear Piercing" : [],
                "Lip Piercing" : [],
                "Hiding Tattoos and Piercing" : [],
                "Self Piercing" : [],
                "Nose Piercing" : [],
            },
        },
        "Pets and Animals" : {
            "Amphibian" : {
                "Frogs" : [],
                "Toads" : [],
                "Newts and Salamanders" : [],
            },
            "Animal Art and Craft" : {
                "Animal Crochet Projects" : [],
                "Animal Felt Projects" : [],
                "Animal Knitting Projects" : [],
                "Animal Paper Art and Craft" : [],
                "Balloon Animals" : [],
                "Beaded Animal Projects" : [],
                "Bird Art and Craft" : [],
                "Cat Art and Craft" : [],
                "Clay Animal Projects" : [],
                "Dinosaur Art and Craft" : [],
                "Dog Art and Craft" : [],
                "Elephant Art and Craft" : [],
                "Fantasy Animal Art and Craft" : [],
                "Horse Art and Craft" : [],
                "Insect Art and Craft" : [],
                "Marine Life Art and Craft" : [],
                "Multimedia Projects for Animals" : [],
                "Painting Animals" : [],
                "Rabbit Art and Craft" : [],
                "Teddy Bear Crafts" : [],
                "Animal Scrapbook Albums" : [],
                "Sewing Toy Animals" : [],
                "Reindeer Art and Craft" : [],
            },
            "Animal Behavior" : {
                "Animal Socialization" : [],
                "Communicating with Animals" : [],
            },
            "Animal Care and Wildlife Occupations" : {
                "Horse Related Employment" : [],
                "Pet Sitting Occupations" : [],
                "Working with Dogs" : [],
            },
            "Animal Rescue" : {
                "Finding Pets" : [],
                "Bird Rescue" : [],
                "Cat Rescue" : [],
                "Dog Rescue" : [],
                "Farm Animal Rescue" : [],
            },
            "Animal Welfare Activism" : {
                "Fundraising for Animals" : [],
                "Animal Awareness Events" : [],
            },
            "Animals and the Law" : {
            },
            "Birds" : {
                "Birdwatching" : [],
                "Feeding Birds" : [],
                "Choosing a Bird" : [],
                "Bird Accessories" : [],
                "Bird Health" : [],
                "Bird Handling and Safety" : [],
                "Training Birds" : [],
                "Attracting Birds" : [],
                "Bird Grooming" : [],
                "Bird Breeding and Nesting" : [],
                "Bird Breeds" : [],
                "Wild Birds" : [],
            },
            "Bugs" : {
                "Mantises" : [],
                "Butterflies and Moths" : [],
                "Ant Pets" : [],
                "Grasshoppers and Crickets" : [],
                "Worms" : [],
                "Spiders and Other Arachnids" : [],
                "Myriapoda" : [],
                "Lady Beetles" : [],
                "Creating Insect Habitats" : [],
            },
            "Cats" : {
                "Grooming Cats" : [],
                "Feline Health" : [],
                "Travel with Cats" : [],
                "Getting a Cat" : [],
                "Feeding Cats" : [],
                "Cat Breeds" : [],
                "Cat Accessories" : [],
                "Breeding Cats" : [],
                "Senior Cat Care" : [],
                "Cleaning Up After Cats" : [],
                "Handling Cats" : [],
                "Cat Behavior" : [],
                "Cat Rescue" : [],
                "Indoor Cat Care" : [],
                "Celebration Events for Cats" : [],
                "Kitten Care" : [],
            },
            "Cleaning Up After Pets" : {
                "Cleaning Aquariums" : [],
                "Cleaning Up After Cats" : [],
                "Pet and Animal Stain Removal" : [],
                "Pet Odors" : [],
                "Removing Pet Hair" : [],
                "Cleaning Up After Dogs" : [],
            },
            "Crustaceans" : {
                "Crabs" : [],
            },
            "Dogs" : {
                "Dog Grooming" : [],
                "Canine Health" : [],
                "Choosing a Dog" : [],
                "Working with Dogs" : [],
                "Dog Toys and Play" : [],
                "Dog Accessories" : [],
                "Feeding Dogs" : [],
                "Breeding Dogs" : [],
                "Senior Dog Care" : [],
                "Dog Breeds" : [],
                "Dog Shows" : [],
                "Exercising Dogs" : [],
                "Dog Sports" : [],
                "Transporting Dogs" : [],
                "Handling Dogs" : [],
                "Cleaning Up After Dogs" : [],
                "Dog Rescue" : [],
                "Celebration Events for Dogs" : [],
                "Day and Vacation Care for Dogs" : [],
                "Dog Behavior" : [],
                "Puppy Care" : [],
            },
            "Fantasy Animals" : {
                "Fantasy Animal Art and Craft" : [],
                "Unicorns" : [],
            },
            "Farm Animals and Livestock" : {
                "Cattle" : [],
                "Goats" : [],
                "Beekeeping" : [],
                "Pigs" : [],
                "Alpacas and Llamas" : [],
                "Sheep" : [],
                "Camels" : [],
                "Poultry" : [],
                "Deer Farming" : [],
                "Donkeys" : [],
                "Ratites" : [],
                "Building Animal Housing" : [],
            },
            "Ferrets" : {
                "Ferret Accessories" : [],
                "Ferret Health" : [],
                "Grooming Ferrets" : [],
            },
            "Fish" : {
                "Aquariums" : [],
                "Fish Health" : [],
                "Feeding Fish" : [],
                "Ponds" : [],
                "Community Fish Care" : [],
                "Breeding Fish" : [],
                "Fish Breeds" : [],
                "Fish Handling and Safety" : [],
            },
            "General Pet Accessories" : {
                "Pet Doors" : [],
                "Building Animal Housing" : [],
                "Pet Hammocks" : [],
            },
            "General Pet Food" : {
            },
            "General Pet Health" : {
                "End of Life Pet Care" : [],
                "Animal First Aid" : [],
            },
            "Hedgehogs" : {
            },
            "Horses" : {
                "Riding" : [],
                "Horse Feeding" : [],
                "Horse Health" : [],
                "Buying and Owning a Horse" : [],
                "Horse Breeding" : [],
                "Horse Grooming" : [],
                "Horse Showing and Competition" : [],
                "Horse Training" : [],
                "Horse Supplies and Accessories" : [],
                "Transporting Horses" : [],
                "Equestrian Fashion" : [],
                "Horse Breeds" : [],
                "Horse Safety" : [],
                "Horse Related Employment" : [],
            },
            "New Pets" : {
            },
            "Parties for Animal Lovers and Pets" : {
                "Celebration Events for Cats" : [],
                "Celebration Events for Dogs" : [],
                "Pets and Christmas" : [],
                "Gifts for Animal Lovers" : [],
            },
            "Pet Hazards" : {
                "Animals in Emergencies" : [],
            },
            "Pets and Vacations" : {
                "Pet Friendly Vacations" : [],
                "Hiring a Pet Sitter" : [],
                "Pet Sitting Occupations" : [],
                "Day and Vacation Care for Dogs" : [],
            },
            "Rabbits" : {
                "Feeding Rabbits" : [],
                "Training Rabbits" : [],
                "Rabbit Health" : [],
                "Handling and Moving Rabbits" : [],
                "Rabbit Grooming" : [],
                "Rabbit Breeds" : [],
                "Rabbit Accessories" : [],
                "Rabbit Socialization" : [],
                "Breeding Rabbits" : [],
                "Rabbit Proofing and Rabbit Safety" : [],
            },
            "Renting and Pets" : {
                "Pets in Apartments" : [],
            },
            "Reptiles" : {
                "Turtles and Tortoises" : [],
                "Snakes" : [],
                "Lizards" : [],
            },
            "Rodents" : {
                "Chinchillas" : [],
                "Gerbils" : [],
                "Guinea Pigs" : [],
                "Hamsters" : [],
                "Mice and Rats" : [],
                "Squirrels" : [],
            },
            "Snails and Slugs" : {
            },
            "Specialist Water Based Pets" : {
            },
            "Transporting Pets" : {
                "Transporting Dogs" : [],
                "Moving with Pets" : [],
                "Travel with Cats" : [],
            },
            "Veterinary Care" : {
            },
            "Wildlife" : {
                "Cetaceans" : [],
                "Monkeys" : [],
                "Big Cats" : [],
                "Creating Habitats for Wildlife" : [],
                "Wolves" : [],
                "Foxes" : [],
                "Marsupials" : [],
                "Raccoons" : [],
                "Squirrels" : [],
                "Wild Birds" : [],
                "Wild Deer" : [],
            },
            "Zoos" : {
            },
        },
        "Philosophy and Religion" : {
            "Atheism" : {
            },
            "Church Management and Maintenance" : {
            },
            "Faith and Belief" : {
                "Prayer" : [],
            },
            "Interfaith Relationships" : {
            },
            "Paranormal Beliefs" : {
                "Ghosts" : [],
                "Card Reading" : [],
                "Palmistry" : [],
                "Astrology" : [],
                "Ouija Boards" : [],
                "Paranormal Magic" : [],
                "Superstitions" : [],
            },
            "Philosophy" : {
                "Positive and Reflective Lifestyles" : [],
            },
            "Religion" : {
                "Islam" : [],
                "Nature & Pagan Beliefs" : [],
                "Buddhism" : [],
                "Hinduism" : [],
                "Confucianism" : [],
                "Taoism" : [],
                "Baha'i" : [],
                "Shinto" : [],
                "Sikhism" : [],
                "Scientology" : [],
                "Christianity" : [],
                "Judaism" : [],
            },
        },
        "Relationships" : {
            "Dating" : {
                "Getting a Date" : [],
                "Ideas for Dates" : [],
                "Long Distance Relationships" : [],
                "Kissing" : [],
                "Love and Romance" : [],
                "Long Term Dating" : [],
                "Family Friends and Dating" : [],
                "Astrology Relationships" : [],
            },
            "Friends" : {
                "Supporting Friends" : [],
                "Forming Friendships" : [],
                "Enjoying Friendship" : [],
                "Handling Friendship Problems" : [],
                "Changing and Losing Friends" : [],
                "Best Friends" : [],
            },
            "LGBT" : {
                "Coming Out as LGBT" : [],
                "LGBT Identity" : [],
                "LGBT Marriage" : [],
                "LGBT Dating" : [],
                "Friends and Family of LGBT" : [],
                "Gender Expression" : [],
            },
            "Maintaining Relationships" : {
            },
            "Managing Conflict and Difficult Interactions" : {
                "Social Nuisances" : [],
                "Managing Arguments" : [],
            },
            "Neighbors" : {
            },
            "Relationship Issues" : {
                "Commitment Issues" : [],
                "Former Relationships" : [],
                "Cheating in Relationships" : [],
                "Breaking Up" : [],
                "Handling Rejection" : [],
            },
            "Single Life" : {
            },
            "Social Interactions" : {
                "Manners" : [],
                "Conversation Skills" : [],
                "Etiquette" : [],
                "Leadership and Mentoring" : [],
                "Social Gatherings" : [],
                "Language Nuances" : [],
                "Clubs" : [],
                "Courteous Presentation" : [],
            },
        },
        "Sports and Fitness" : {
            "Cleaning Sports Gear" : {
                "Cleaning Sports Clothes" : [],
                "Cleaning Sports Shoes" :[],
            },
            "For the Fan" : {
                "Fans of Baseball" : [],
                "Fans of Football" : [],
                "Fans of Hockey" : [],
                "Fans of Basketball" :[],
            },
            "Individual Sports" : {
                "Bicycling" : [],
                "Racket Sports" : [],
                "Surfing" : [],
                "Swimming and Diving" : [],
                "Parkour" : [],
                "Inline and Roller Skating" : [],
                "Trampoline" : [],
                "Cue Sports" : [],
                "Bowling" : [],
                "Combat Sports" : [],
                "Archery" : [],
                "Ice and Figure Skating" : [],
                "Snow Skiing" : [],
                "Water Skiing" : [],
                "Track and Field" : [],
                "Snowboarding" : [],
                "Baton Twirling" : [],
                "Golf" : [],
                "Skateboarding" : [],
                "Air Sports" : [],
                "Gymnastics" : [],
                "Canoes, Kayaks, and Rowboats" :[],
            },
            "Olympics" : {
            },
            "Outdoor Recreation" : {
                "Backpacking and Hiking" : [],
                "Camping" : [],
                "Fishing" : [],
                "Hunting" : [],
                "Outdoor Safety" : [],
                "Climbing" : [],
                "Scouting & Other Youth Groups" : [],
                "Winter Outdoor Activities" : [],
                "Caving and Spelunking" : [],
                "Guns and Shooting" : [],
                "Enjoying the Great Outdoors" : [],
                "Knot Tying" : [],
                "Enjoying the Beach" : [],
                "Map and Orienteering Skills" : [],
                "Outdoor Treasure Hunting" : [],
                "Wilderness First Aid" : [],
                "Parks" : [],
                "Water Recreation" :[],
            },
            "Personal Fitness" : {
                "Calisthenic Exercises" : [],
                "Cardio Exercises" : [],
                "Warm Ups Stretching and Flexibility" : [],
                "Gym" : [],
                "Hooping" : [],
                "Running for Fitness" : [],
                "Walking for Fitness" : [],
                "Motivation to Exercise" : [],
                "Building Muscle & Strength" : [],
                "Pilates" :[],
            },
            "Sports Health" : {
                "Sports and Pain Management" : [],
                "Soft Tissue Injuries" : [],
                "Cooling Down (Sports)" : [],
                "Warming Up (Sports)" : [],
                "Menstruation and Sports" : [],
                "Exercising During Pregnancy" :[],
            },
            "Sports Leadership" : {
            },
            "Team Sports" : {
                "Baseball" : [],
                "Ice Hockey" : [],
                "Table Tennis" : [],
                "Volleyball" : [],
                "Water Polo" : [],
                "Cheerleading" : [],
                "Cricket" : [],
                "Softball" : [],
                "Field Hockey and Lacrosse" : [],
                "Basketball" : [],
                "Dodgeball" : [],
                "Football" : [],
                "Netball" : [],
                "Airsoft" : [],
                "Soccer" : [],
                "Paintball" : [],
                "Rowing" : [],
                "Handball" :[],
            },
        },
        "Travel" : {
            "Cleaning Travel Gear" :{

            },
            "Destinations" :{
                "Australasia & Oceania" : [],
                "Middle East" : [],
                "South America" : [],
                "Central America & Caribbean" : [],
                "North America" : [],
                "Asia" : [],
                "Europe" : [],
                "Africa" : [],
            },
            "Family Vacations" :{

            },
            "National Parks" :{
                "National Parks (USA)" : [],
            },
            "Travel and Traditional Celebrations" :{

            },
            "Travel Health" :{
                "Air Travel Health" : [],
            },
            "Travel Tips" :{
                "Living Overseas" : [],
                "Official Travel Documentation" : [],
                "Planning Travel" : [],
                "Public Transport" : [],
                "Road & Rail Travel" : [],
                "Travel Packing" : [],
                "Reduce Travel Cost" : [],
                "Travel Safety & Security" : [],
                "Air Travel" : [],
                "Travel Cruises" : [],
                "Lodging" : [],
            },
        },
        "Work World" : {
            "Consultancy Freelance and Contracting" : {
                "Digital Nomads" : [],
                "Freelance Artists" : [],
                "Freelance Writing" : [],
                "Freelance Marketplace Websites" : [],
                "Home Businesses" : [],
                "Pricing Goods and Services" : [],
                "Working from Home" : [],
            },
            "Job Search" : {
                "Job Search for Youth" : [],
                "Internships" : [],
                "Dealing with Job Rejections" : [],
                "Employment Websites" : [],
                "Job Application Documents" : [],
                "Job Interviews" : [],
                "Job Offers" : [],
                "Job References" : [],
                "Job Fairs" : [],
            },
            "Job Strategies" : {
                "Job Attendance" : [],
                "Work Schedules" : [],
            },
            "Leadership and Mentoring" : {
            },
            "Meetings" : {
                "Conferences" : [],
            },
            "Occupations" : {
                "Careers in the Military" : [],
                "Careers in Government" : [],
                "Domestic Assistance" : [],
                "Teaching" : [],
                "Fashion and Entertainment" : [],
                "Visual & Written Media" : [],
                "Farming" : [],
                "Health Care" : [],
                "Sporting Careers" : [],
                "Information Technology Careers" : [],
                "Legal Careers" : [],
                "Tradesman Occupations" : [],
                "Finance Careers" : [],
                "Administrative Careers" : [],
                "Transport Careers" : [],
                "Sales Occupations" : [],
                "Architecture and Design Occupations" : [],
                "Animal Care and Wildlife Occupations" : [],
                "Political Occupations" : [],
                "Hospitality and Tourism Careers" : [],
                "Careers in Art" : [],
                "Marketing Careers" : [],
            },
            "Office Skills" : {
                "Typing Skills" : [],
            },
            "Workplace Conflicts Coping and Issues" : {
                "Interacting with Bosses" : [],
                "Interacting with Colleagues" : [],
                "Job Loss and Change" : [],
                "Leisure at Work" : [],
            },
            "Workplace Management Skills" : {
                "Improving Employee Morale" : [],
                "Interacting with Employees" : [],
                "Workplace Health and Safety" : [],
                "Project Management" : [],
                "Recruitment" : [],
            },
            "Workplace Theft" : {
            },
        },
        "Youth" : {
            "Health for Teens and Kids" : {
                "Emotional Health and Well Being" : [],
                "Puberty and Reproductive Health" : [],
                "Youth Diets and Nutrition" : [],
                "Teenage Pregnancy" : [],
            },
            "Keeping Safe" : {
                "Keeping Safe Online" : [],
                "Dealing with Bullying" : [],
            },
            "Money Management for Young People" : {
                "Money Saving Hints for Young People" : [],
                "Making Money in School" : [],
                "Job Search for Youth" : [],
                "Youth Businesses" : [],
            },
            "Personal Care for Youth" : {
                "Acne" : [],
                "Youth Fashion" : [],
                "Youth Grooming" : [],
            },
            "Personal Space" : {
                "Bedroom Styles for Youth" : [],
                "Closet and Wardrobe Organization (Youth)" : [],
                "Private Space for Young People" : [],
            },
            "Personality Types and Youth Style" : {
                "Goth" : [],
                "Punk" : [],
                "Artistic Styles" : [],
                "Nonconformist Styles" : [],
                "Urban Styles" : [],
                "Eco Youth Styles" : [],
                "Intellectual Types" : [],
                "Japanese Fashion" : [],
                "Scene" : [],
                "Emo" : [],
                "Character Style Imitation" : [],
                "Tomboy Behavior" : [],
                "Animal Imitation" : [],
                "Fantasy Imitation" : [],
            },
            "School Stuff" : {
                "Managing Time During School Years" : [],
                "School Leadership" : [],
                "School Discipline" : [],
                "Surviving School" : [],
                "Academic Dishonesty" : [],
                "School Food" : [],
                "Class Distractions" : [],
                "End of School" : [],
                "Lockers" : [],
                "Dealing with Teachers" : [],
                "School Popularity" : [],
                "School Field Trips" : [],
                "Back to School" : [],
                "School Materials" : [],
            },
            "Social Events for Youth" : {
                "Dances" : [],
                "Proms" : [],
                "Teen Holidays" : [],
                "Teen Parties" : [],
                "Sleep Overs" : [],
            },
            "Social Interactions for Youth" : {
                "Best Friends Teens and Kids" : [],
                "Friendship Problems" : [],
                "Making Friends" : [],
                "Making Up with Friends" : [],
                "Managing Youth Conflict" : [],
            },
            "Youth and Family" : {
                "Siblings" : [],
                "You and Your Parents" : [],
            },
            "Youth Dating" : {
                "First Dates" : [],
                "Going Steady" : [],
                "Youth Flirting" : [],
                "Getting a Date (Youth)" : [],
                "Kissing (Youth)" : [],
                "Dating and Friends" : [],
                "Youth Relationship Issues" : [],
                "Crushes" : [],
            },
        },
    }
}